import "./globals.css";
import Navbar from "./nav/navbar";

import { Providers } from "@/redux/provider";

export const metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <Providers>
          <Navbar />
          <main className="inside-container px-4 mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
