export const metadata = {
    title: "Product Details",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <>{children}</>
    );
  }
  